# Generated by Django 4.2.6 on 2023-10-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('strength', models.IntegerField(verbose_name='сила')),
                ('health', models.IntegerField(verbose_name='здоровье')),
                ('mana', models.IntegerField(verbose_name='мана')),
                ('agility', models.IntegerField(verbose_name='ловкость')),
                ('luck', models.IntegerField(verbose_name='удача')),
            ],
        ),
        migrations.CreateModel(
            name='Mage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('strength', models.IntegerField(verbose_name='сила')),
                ('health', models.IntegerField(verbose_name='здоровье')),
                ('mana', models.IntegerField(verbose_name='мана')),
                ('agility', models.IntegerField(verbose_name='ловкость')),
                ('luck', models.IntegerField(verbose_name='удача')),
            ],
        ),
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('strength', models.IntegerField(verbose_name='сила')),
                ('health', models.IntegerField(verbose_name='здоровье')),
                ('mana', models.IntegerField(verbose_name='мана')),
                ('agility', models.IntegerField(verbose_name='ловкость')),
                ('luck', models.IntegerField(verbose_name='удача')),
            ],
        ),
        migrations.CreateModel(
            name='Warrior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('strength', models.IntegerField(verbose_name='сила')),
                ('health', models.IntegerField(verbose_name='здоровье')),
                ('mana', models.IntegerField(verbose_name='мана')),
                ('agility', models.IntegerField(verbose_name='ловкость')),
                ('luck', models.IntegerField(verbose_name='удача')),
            ],
        ),
    ]
