# Generated by Django 4.2.6 on 2023-10-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archer',
            options={'verbose_name': 'Лучник', 'verbose_name_plural': 'Лучники'},
        ),
        migrations.AlterModelOptions(
            name='mage',
            options={'verbose_name': 'Маг', 'verbose_name_plural': 'Маги'},
        ),
        migrations.AlterModelOptions(
            name='priest',
            options={'verbose_name': 'Жрец', 'verbose_name_plural': 'Жрецы'},
        ),
        migrations.AlterModelOptions(
            name='warrior',
            options={'verbose_name': 'Воин', 'verbose_name_plural': 'Воины'},
        ),
    ]
