version: "3.7"

services:
  test_app:
    container_name: party_app
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: run
    volumes:
      - .:/app/
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env
    ports:
      - 8006:8006


volumes:
  postgres-data:
